checkpoint_frequency: null
data_dir: /mnt/d/project/Java/rtree_construct/preExperData/RTreeTokenContext
dataset: WikiText2
epochs: 50
learning_rate: 0.025
model_dir: weights/skipgram_preExper
model_name: skipgram
optimizer: Adam
shuffle: true
train_batch_size: 96
train_steps: null
val_batch_size: 96
val_steps: null
