model_name: cbow
#model_name: cbow, skipgram, combined
filter: False
model_dir: weights/cbow_preExper
epochs: 300

dataset: RandomGenerate
# 处理后的带有 label 的 R-tree 的 node token 上下文
data_dir: /mnt/d/project/Java/rtree_construct/preExperData/RTreeTokenContext
train_batch_size: 96
val_batch_size: 96
shuffle: True

optimizer: Adam
learning_rate: 0.025

train_steps: 
val_steps:
checkpoint_frequency: 


