# model_name: cbow, skipgram, combined
model_name: cbow
# 是否需要筛选数据，即将 NL 与 L 分开处理（filter=True）
filter: False
model_dir: weights/cbow_preExper
epochs: 1000

dataset: RandomGenerate
# 处理后的带有 label 的 R-tree 的 node token 上下文
train_data_dir: /mnt/d/project/Java/rtree_construct/preExperData/RTreeTokenContextAll/train
val_data_dir: /mnt/d/project/Java/rtree_construct/preExperData/RTreeTokenContextAll/val
train_batch_size: 256
val_batch_size: 256
shuffle: True

optimizer: Adam
learning_rate: 0.05

train_steps: 
val_steps:
checkpoint_frequency: 


