model_name: cbow
#model_name: cbow, skip, combine

dataset: WikiText2
data_dir: /mnt/d/project/python/ARPN4ITS/dataPreprocess/test/
train_batch_size: 96
val_batch_size: 96
shuffle: True

optimizer: Adam
learning_rate: 0.025
epochs: 5
train_steps: 
val_steps: 

checkpoint_frequency: 
model_dir: weights/cbow_WikiText2
